@namespace
class SpriteKind:
    keepitup = SpriteKind.create()

def on_on_overlap(sprite, otherSprite):
    if controller.A.is_pressed():
        animation.run_image_animation(mySprite,
            [img("""
                    ..........eeeeee................
                                .......eeeeeeeeeee..............
                                .....eeeeeeeeeeeeee.............
                                ....eeeeeeeeeeeeeeee............
                                ...eeeeeeeeeeeeeeeeee...........
                                ..eeeeeeeeeeeeeeeeeeee..........
                                .eeeeeeeeeeeeeeeeeeeee..........
                                .eeeeeeeeeeeeeeeeeeeeee.........
                                eeeeeeeeeeeeeeeeeeeeeee.........
                                eeeeeeeeeeeeeeeeeeeeeee.........
                                eeeeeeeeeeeeeeeeeeeeeeee........
                                eeeeeeeeeeeeeeeeeeeeeeee........
                                eeeeeeeeeeeeeeeeeeeeeeee........
                                eeeeeeeeeeeeeeeeeeeeeeee........
                                eeeeeeeeeeeeeeeeeeeeeeee........
                                .eeeeeeeeeeeeeeeeeeeeeee........
                                .eeeeeeeeeeeeeeeeeeeeeeee.......
                                ..eeeeeeeeeeeeeeeeeeeeeee.......
                                ...eeeeeeeeeeeeeeeeeeeeee.......
                                .....eeeeeeeeeeeeeeeeeeee.......
                                .......eeeeeeeeeeeeeeeeee.......
                                ............eeeeeeeeeeeee.......
                                ..............eeeeeeeeeeee......
                                .................eeeeeeeeee.....
                                .......................eeeeeeee.
                                ........................eeeeeeee
                                .........................eeeeeee
                                .........................eeeeeee
                                .........................eeeeeee
                                .........................eeeeeee
                                ..........................eeeeee
                                ................................
                """),
                img("""
                    .........................eeeeee.
                                ........................eeeeeee.
                                ........................eeeeeee.
                                ........................eeeeeee.
                                ........................eeeeeee.
                                .......................eeeeeeee.
                                ......................eeeeeeee..
                                ................eeeeeeeeee......
                                ..........eeeeeeeeeeeeeee.......
                                .......eeeeeeeeeeeeeeeee........
                                .....eeeeeeeeeeeeeeeeeee........
                                ....eeeeeeeeeeeeeeeeeeee........
                                ...eeeeeeeeeeeeeeeeeeeee........
                                ..eeeeeeeeeeeeeeeeeeeeee........
                                .eeeeeeeeeeeeeeeeeeeeeee........
                                .eeeeeeeeeeeeeeeeeeeeee.........
                                eeeeeeeeeeeeeeeeeeeeeee.........
                                eeeeeeeeeeeeeeeeeeeeeee.........
                                eeeeeeeeeeeeeeeeeeeeee..........
                                eeeeeeeeeeeeeeeeeeeeee..........
                                eeeeeeeeeeeeeeeeeeeee...........
                                eeeeeeeeeeeeeeeeeeeee...........
                                .eeeeeeeeeeeeeeeeeeee...........
                                .eeeeeeeeeeeeeeeeeeee...........
                                .eeeeeeeeeeeeeeeeeeee...........
                                ..eeeeeeeeeeeeeeeeee............
                                ..eeeeeeeeeeeeeeeeee............
                                ...eeeeeeeeeeeeeeee.............
                                ....eeeeeeeeeeeeeee.............
                                .....eeeeeeeeeeeee..............
                                ......eeeeeeeeeee...............
                                ........eeeeeee.................
                """),
                img("""
                    ................................
                                eeeeee..........................
                                eeeeeee.........................
                                eeeeeee.........................
                                eeeeeee.........................
                                eeeeeee.........................
                                eeeeeeee........................
                                .eeeeeeee.......................
                                .....eeeeeeeeee.................
                                ......eeeeeeeeeeee..............
                                .......eeeeeeeeeeeee............
                                .......eeeeeeeeeeeeeeeeee.......
                                .......eeeeeeeeeeeeeeeeeeee.....
                                .......eeeeeeeeeeeeeeeeeeeeee...
                                .......eeeeeeeeeeeeeeeeeeeeeee..
                                .......eeeeeeeeeeeeeeeeeeeeeeee.
                                ........eeeeeeeeeeeeeeeeeeeeeee.
                                ........eeeeeeeeeeeeeeeeeeeeeeee
                                ........eeeeeeeeeeeeeeeeeeeeeeee
                                ........eeeeeeeeeeeeeeeeeeeeeeee
                                ........eeeeeeeeeeeeeeeeeeeeeeee
                                ........eeeeeeeeeeeeeeeeeeeeeeee
                                .........eeeeeeeeeeeeeeeeeeeeeee
                                .........eeeeeeeeeeeeeeeeeeeeeee
                                .........eeeeeeeeeeeeeeeeeeeeee.
                                ..........eeeeeeeeeeeeeeeeeeeee.
                                ..........eeeeeeeeeeeeeeeeeeee..
                                ...........eeeeeeeeeeeeeeeeee...
                                ............eeeeeeeeeeeeeeee....
                                .............eeeeeeeeeeeeee.....
                                ..............eeeeeeeeeee.......
                                ................eeeeee..........
                """),
                img("""
                    .........................eeeeee.
                                ........................eeeeeee.
                                ........................eeeeeee.
                                ........................eeeeeee.
                                ........................eeeeeee.
                                .......................eeeeeeee.
                                ......................eeeeeeee..
                                ................eeeeeeeeee......
                                ..........eeeeeeeeeeeeeee.......
                                .......eeeeeeeeeeeeeeeee........
                                .....eeeeeeeeeeeeeeeeeee........
                                ....eeeeeeeeeeeeeeeeeeee........
                                ...eeeeeeeeeeeeeeeeeeeee........
                                ..eeeeeeeeeeeeeeeeeeeeee........
                                .eeeeeeeeeeeeeeeeeeeeeee........
                                .eeeeeeeeeeeeeeeeeeeeee.........
                                eeeeeeeeeeeeeeeeeeeeeee.........
                                eeeeeeeeeeeeeeeeeeeeeee.........
                                eeeeeeeeeeeeeeeeeeeeee..........
                                eeeeeeeeeeeeeeeeeeeeee..........
                                eeeeeeeeeeeeeeeeeeeee...........
                                eeeeeeeeeeeeeeeeeeeee...........
                                .eeeeeeeeeeeeeeeeeeee...........
                                .eeeeeeeeeeeeeeeeeeee...........
                                .eeeeeeeeeeeeeeeeeeee...........
                                ..eeeeeeeeeeeeeeeeee............
                                ..eeeeeeeeeeeeeeeeee............
                                ...eeeeeeeeeeeeeeee.............
                                ....eeeeeeeeeeeeeee.............
                                .....eeeeeeeeeeeee..............
                                ......eeeeeeeeeee...............
                                ........eeeeeee.................
                """)],
            100,
            False)
        pause(100)
        mySprite.set_image(img("""
            ..........eeeeee................
                        .......eeeeeeeeeee..............
                        .....eeeeeeeeeeeeee.............
                        ....eeeeeeeeeeeeeeee............
                        ...eeeeeeeeeeeeeeeeee...........
                        ..eeeeeeeeeeeeeeeeeeee..........
                        .eeeeeeeeeeeeeeeeeeeee..........
                        .eeeeeeeeeeeeeeeeeeeeee.........
                        eeeeeeeeeeeeeeeeeeeeeee.........
                        eeeeeeeeeeeeeeeeeeeeeee.........
                        eeeeeeeeeeeeeeeeeeeeeeee........
                        eeeeeeeeeeeeeeeeeeeeeeee........
                        eeeeeeeeeeeeeeeeeeeeeeee........
                        eeeeeeeeeeeeeeeeeeeeeeee........
                        eeeeeeeeeeeeeeeeeeeeeeee........
                        .eeeeeeeeeeeeeeeeeeeeeee........
                        .eeeeeeeeeeeeeeeeeeeeeeee.......
                        ..eeeeeeeeeeeeeeeeeeeeeee.......
                        ...eeeeeeeeeeeeeeeeeeeeee.......
                        .....eeeeeeeeeeeeeeeeeeee.......
                        .......eeeeeeeeeeeeeeeeee.......
                        ............eeeeeeeeeeeee.......
                        ..............eeeeeeeeeeee......
                        .................eeeeeeeeee.....
                        .......................eeeeeeee.
                        ........................eeeeeeee
                        .........................eeeeeee
                        .........................eeeeeee
                        .........................eeeeeee
                        .........................eeeeeee
                        ..........................eeeeee
                        ................................
        """))
sprites.on_overlap(SpriteKind.keepitup, SpriteKind.player, on_on_overlap)

def on_on_overlap2(sprite2, otherSprite2):
    if controller.A.is_pressed():
        myDart.throw_dart()
        myDart.gravity += randint(200, -200)
        myDart.angle += 0
        myDart.angle += randint(360, -360)
        statusbar.value += 3
        info.change_score_by(1)
    else:
        statusbar.value += -5
sprites.on_overlap(SpriteKind.player, SpriteKind.keepitup, on_on_overlap2)

statusbar: StatusBarSprite = None
mySprite: Sprite = None
myDart: Dart = None
info.start_countdown(240)
tiles.set_current_tilemap(tilemap("""
    level1
"""))
myDart = darts.create(img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . 2 b 1 . . . . . . . 
            . . . . . . 2 2 3 . . . . . . . 
            . . . . . . 2 2 2 . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . .
    """),
    SpriteKind.keepitup)
mySprite = sprites.create(img("""
        ..........eeeeee................
            .......eeeeeeeeeee..............
            .....eeeeeeeeeeeeee.............
            ....eeeeeeeeeeeeeeee............
            ...eeeeeeeeeeeeeeeeee...........
            ..eeeeeeeeeeeeeeeeeeee..........
            .eeeeeeeeeeeeeeeeeeeee..........
            .eeeeeeeeeeeeeeeeeeeeee.........
            eeeeeeeeeeeeeeeeeeeeeee.........
            eeeeeeeeeeeeeeeeeeeeeee.........
            eeeeeeeeeeeeeeeeeeeeeeee........
            eeeeeeeeeeeeeeeeeeeeeeee........
            eeeeeeeeeeeeeeeeeeeeeeee........
            eeeeeeeeeeeeeeeeeeeeeeee........
            eeeeeeeeeeeeeeeeeeeeeeee........
            .eeeeeeeeeeeeeeeeeeeeeee........
            .eeeeeeeeeeeeeeeeeeeeeeee.......
            ..eeeeeeeeeeeeeeeeeeeeeee.......
            ...eeeeeeeeeeeeeeeeeeeeee.......
            .....eeeeeeeeeeeeeeeeeeee.......
            .......eeeeeeeeeeeeeeeeee.......
            ............eeeeeeeeeeeee.......
            ..............eeeeeeeeeeee......
            .................eeeeeeeeee.....
            .......................eeeeeeee.
            ........................eeeeeeee
            .........................eeeeeee
            .........................eeeeeee
            .........................eeeeeee
            .........................eeeeeee
            ..........................eeeeee
            ................................
    """),
    SpriteKind.player)
controller.move_sprite(mySprite, 100, 0)
myDart.throw_dart()
myDart.set_position(0, 0)
mySprite.set_stay_in_screen(True)
myDart.set_stay_in_screen(False)
myDart.set_bounce_on_wall(True)
statusbar = statusbars.create(20, 4, StatusBarKind.health)
scene.camera_follow_sprite(mySprite)
mySprite.set_position(6, 230)
myDart.pow = 4000
statusbar.value += 1000